### Global ARGs Variables
# Provide the repository's HTTPS URL, since the SSL is not supported by defult.
ARG MONGO_PLUGIN_GIT_URL='https://github.com/JamesOsgood/mongodb-grafana.git'
ARG MONGO_PLUGIN_GIT_DIR='mongodb-grafana'

# Package names (space seperated).
ARG PACKAGES_TO_INSTALL="git tini"
ARG WORKINGDIRECTORY=/
##############################################

FROM node:12.22.12-alpine3.15 AS build
ARG MONGO_PLUGIN_GIT_URL
ARG MONGO_PLUGIN_GIT_DIR
ARG PACKAGES_TO_INSTALL
ARG WORKINGDIRECTORY

WORKDIR ${WORKINGDIRECTORY}
RUN apk add --no-cache ${PACKAGES_TO_INSTALL}      && \
      rm -rf /var/cache/apk/*           && \
      git clone ${MONGO_PLUGIN_GIT_URL} && \
      cd ${MONGO_PLUGIN_GIT_DIR}        && \
      npm install
############################################

FROM node:12.22.12-alpine3.15 AS to-run
ARG WORKINGDIRECTORY
ARG MONGO_PLUGIN_GIT_DIR

ENV MONGO_PLUGIN_GIT_DIR        $MONGO_PLUGIN_GIT_DIR

WORKDIR ${WORKINGDIRECTORY}
COPY --from=build  ${WORKINGDIRECTORY}/${MONGO_PLUGIN_GIT_DIR}/ ./${MONGO_PLUGIN_GIT_DIR}/
COPY --from=build /sbin/tini /sbin/tini

WORKDIR ${WORKINGDIRECTORY}/${MONGO_PLUGIN_GIT_DIR}

EXPOSE 3333

ENTRYPOINT ["/sbin/tini", "--"]

CMD npm run server
